# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_monorepo:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
#       - run: git config pull.rebase true 
#       - run: git config --local user.email "$(git log --format='%ae' HEAD^!)"
#       - run: git config --local user.name "$(git log --format='%an' HEAD^!)"
#       - run: git remote add -f celo-monorepo https://github.com/celo-org/celo-monorepo.git
#       - run: git merge -s ours --no-commit --allow-unrelated-histories celo-monorepo/master
#       - run: git read-tree --prefix=celo-monorepo/ -u celo-monorepo/master
#       - run: git pull -s subtree celo-monorepo master
      - name: Get monorepo dependencies
        working-directory: ./celo-monorepo
        run: yarn lerna
      - name: Build monorepo
        working-directory: ./celo-monorepo
        run: yarn lerna build --ignore docs
      
  build:

    runs-on: ubuntu-latest
    
    needs: build_monorepo

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
